#!/usr/bin/env python3
"""Render the authoritative Markdown palette table as an editable SVG overview."""

from __future__ import annotations

import argparse
import html
import re
import sys
from dataclasses import dataclass
from pathlib import Path


ROW_RE = re.compile(
    r"^\| `(?P<id>[a-z0-9-]+)` \| "
    r"(?P<name>.+?) — (?P<codes>(?:`#[0-9A-F]{6}`(?:, )?)+) "
    r"\| (?P<use>.+?) \|$",
    re.MULTILINE,
)
HEX_RE = re.compile(r"#[0-9A-F]{6}")


@dataclass(frozen=True)
class Palette:
    palette_id: str
    name: str
    colors: tuple[str, ...]
    use: str


def parse_palettes(path: Path) -> list[Palette]:
    text = path.read_text(encoding="utf-8")
    palettes = [
        Palette(
            palette_id=match.group("id"),
            name=match.group("name"),
            colors=tuple(HEX_RE.findall(match.group("codes"))),
            use=match.group("use"),
        )
        for match in ROW_RE.finditer(text)
    ]
    if not palettes:
        raise ValueError(f"no palette rows found in {path}")
    ids = [palette.palette_id for palette in palettes]
    if len(ids) != len(set(ids)):
        raise ValueError("palette IDs must be unique")
    return palettes


def is_very_light(color: str) -> bool:
    red, green, blue = (
        int(color[index : index + 2], 16) / 255
        for index in (1, 3, 5)
    )
    luminance = 0.2126 * red + 0.7152 * green + 0.0722 * blue
    return luminance > 0.9


def render_svg(palettes: list[Palette]) -> str:
    width = 1600
    columns = 2
    rows = (len(palettes) + columns - 1) // columns
    card_width = 740
    card_height = 88
    left = 40
    top = 100
    gap_x = 40
    height = top + rows * card_height + 60
    lines = [
        '<svg xmlns="http://www.w3.org/2000/svg" '
        f'width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
        "  <!-- Generated by scripts/render_palette_strips.py. "
        "Edit references/scientific-figure-palettes.md, not this file. -->",
        '  <rect id="background" width="100%" height="100%" fill="#FFFFFF"/>',
        '  <g id="title" font-family="Arial, Helvetica, sans-serif">',
        '    <text x="40" y="40" font-size="26" font-weight="700" '
        'fill="#0D1B2A">Scientific Figure Palettes</text>',
        '    <text x="40" y="68" font-size="15" fill="#495057">'
        "Preferred screenshot selections first · one strip per figure · "
        "cool or neutral structure with sparse accents</text>",
        "  </g>",
    ]
    for index, palette in enumerate(palettes):
        column = index % columns
        row = index // columns
        x = left + column * (card_width + gap_x)
        y = top + row * card_height
        strip_x = x + 245
        strip_y = y + 4
        strip_width = 495
        strip_height = 52
        swatch_width = strip_width / len(palette.colors)
        lines.extend(
            [
                f'  <g id="{palette.palette_id}" '
                'font-family="Arial, Helvetica, sans-serif">',
                f'    <text x="{x}" y="{y + 25}" font-size="16" '
                f'font-weight="700" fill="#0D1B2A">{html.escape(palette.name)}</text>',
                f'    <text x="{x}" y="{y + 48}" font-size="12" '
                f'fill="#6C757D">{html.escape(palette.palette_id)}</text>',
            ]
        )
        for color_index, color in enumerate(palette.colors):
            rect_x = strip_x + color_index * swatch_width
            stroke = ' stroke="#CED4DA" stroke-width="1"' if is_very_light(color) else ""
            lines.append(
                f'    <rect id="{palette.palette_id}-{color[1:].lower()}" '
                f'x="{rect_x:.2f}" y="{strip_y}" width="{swatch_width:.2f}" '
                f'height="{strip_height}" fill="{color}"{stroke}/>'
            )
        use = palette.use if len(palette.use) <= 105 else palette.use[:102] + "..."
        lines.extend(
            [
                f'    <text x="{x}" y="{y + 72}" font-size="11" '
                f'fill="#495057">{html.escape(use)}</text>',
                "  </g>",
            ]
        )
    lines.extend(
        [
            f'  <text x="40" y="{height - 24}" '
            'font-family="Arial, Helvetica, sans-serif" font-size="12" '
            'fill="#6C757D">Hex codes and semantic role mappings are authoritative '
            "in references/scientific-figure-palettes.md.</text>",
            "</svg>",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    root = Path(__file__).resolve().parent.parent
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--reference",
        type=Path,
        default=root / "references" / "scientific-figure-palettes.md",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=root / "assets" / "palettes" / "scientific-figure-palettes.svg",
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    try:
        expected = render_svg(parse_palettes(args.reference.resolve()))
    except (OSError, ValueError) as exc:
        print(f"ERROR: {exc}")
        return 1

    output = args.output.resolve()
    if args.check:
        if not output.is_file() or output.read_text(encoding="utf-8") != expected:
            print(f"ERROR: palette SVG is stale: {output}")
            return 1
        print("Palette SVG is up to date.")
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(expected, encoding="utf-8")
    print(f"Rendered {output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
